# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-14 01:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, verbose_name='手机')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '管理员',
            },
        ),
        migrations.CreateModel(
            name='ScenicSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='景点名')),
                ('address', models.CharField(max_length=255, verbose_name='景点位置')),
                ('scenic_img', models.CharField(max_length=255, verbose_name='相关图片')),
                ('introduction', models.TextField(verbose_name='景点介绍')),
            ],
            options={
                'verbose_name': '景点',
            },
        ),
        migrations.AddField(
            model_name='adminuser',
            name='scenicspot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adminuser', to='administrator.ScenicSpot'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adminuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
