# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-14 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20190114_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='scenicspot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adminuser', to='administrator.ScenicSpot'),
        ),
    ]
