# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-15 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20190114_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenicTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price', models.FloatField(default=40.0, verbose_name='票价')),
                ('tickets_one_day', models.IntegerField(default=10000, verbose_name='每日限流')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='票价信息规定时间')),
                ('is_opened', models.BooleanField(default=True, verbose_name='是否开放')),
                ('is_used', models.BooleanField(default=True, verbose_name='是否有效')),
                ('scenic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrator.ScenicSpot', verbose_name='景区')),
            ],
            options={
                'verbose_name': '景点相关信息',
            },
        ),
    ]
