# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-15 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_scenicticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenicticket',
            name='scenic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scenic_ticket', to='administrator.ScenicSpot', verbose_name='景区'),
        ),
    ]
