# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-15 10:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0006_auto_20190115_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, verbose_name='手机')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('scenicspot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='administrator.ScenicSpot', verbose_name='所属景点')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '员工',
            },
        ),
    ]
