# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-15 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_adminuser',
            field=models.BooleanField(default=True, verbose_name='是否为管理员'),
        ),
    ]
