# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-11 08:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190111_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superuser',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='superuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
