# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-11 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190111_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
