# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-11 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_superuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superuser',
            name='email',
        ),
    ]
