# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-11 11:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20190111_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13, unique=True)),
            ],
            options={
                'verbose_name': '管理员',
            },
        ),
        migrations.CreateModel(
            name='ScenicSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenic_name', models.CharField(max_length=255, unique=True, verbose_name='景区名称')),
                ('address', models.CharField(max_length=255, verbose_name='景区地址')),
                ('scenic_desc', models.TextField(verbose_name='景区描述')),
                ('scenic_img', models.TextField(verbose_name='景区相关图片')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '景点',
            },
        ),
        migrations.AddField(
            model_name='adminuser',
            name='scenic_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='app.ScenicSpot', verbose_name='景区'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
