# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-11 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190111_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='superadmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='superadmin', to=settings.AUTH_USER_MODEL),
        ),
    ]
