# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-12 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190111_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
