# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-15 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='scenicspot',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
